# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.runs/synth_1/top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.cache/wt [current_project]
set_property parent.project_path /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/maji/Videos/MIPS32/Sort/SORT/data_file.coe
add_files /home/maji/Videos/MIPS32/Sort/SORT/sort-ins.coe
read_verilog -library xil_defaultlib {
  /home/maji/Videos/MIPS32/Sort/design/ALU.v
  /home/maji/Videos/MIPS32/Sort/design/ALU_function.v
  /home/maji/Videos/MIPS32/Sort/design/AND.v
  /home/maji/Videos/MIPS32/Sort/design/AND_32.v
  /home/maji/Videos/MIPS32/Sort/design/Adder_32.v
  /home/maji/Videos/MIPS32/Sort/design/EightBitAdder.v
  /home/maji/Videos/MIPS32/Sort/design/EightBitSubtractor.v
  /home/maji/Videos/MIPS32/Sort/design/FourBitAdder.v
  /home/maji/Videos/MIPS32/Sort/design/HAMM.v
  /home/maji/Videos/MIPS32/Sort/design/HAMM_32.v
  /home/maji/Videos/MIPS32/Sort/design/IN_REG.v
  /home/maji/Videos/MIPS32/Sort/design/LMD.v
  /home/maji/Videos/MIPS32/Sort/design/MUX.v
  /home/maji/Videos/MIPS32/Sort/design/MUX1.v
  /home/maji/Videos/MIPS32/Sort/design/MUX_16_to_1.v
  /home/maji/Videos/MIPS32/Sort/design/MUX_2_to_1.v
  /home/maji/Videos/MIPS32/Sort/design/MUX_32_to_1.v
  /home/maji/Videos/MIPS32/Sort/design/MUX_4_to_1.v
  /home/maji/Videos/MIPS32/Sort/design/MUX_8_to_1.v
  /home/maji/Videos/MIPS32/Sort/design/OR.v
  /home/maji/Videos/MIPS32/Sort/design/OR_32.v
  /home/maji/Videos/MIPS32/Sort/design/PC.v
  /home/maji/Videos/MIPS32/Sort/design/RB.v
  /home/maji/Videos/MIPS32/Sort/design/SixteenAdder.v
  /home/maji/Videos/MIPS32/Sort/design/XOR.v
  /home/maji/Videos/MIPS32/Sort/design/XOR_32.v
  /home/maji/Videos/MIPS32/Sort/design/arithmetic_right_shift_32bit.v
  /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.srcs/sources_1/new/clock_div.v
  /home/maji/Videos/MIPS32/Sort/design/comparator_32.v
  /home/maji/Videos/MIPS32/Sort/design/complementer.v
  /home/maji/Videos/MIPS32/Sort/design/control_path.v
  /home/maji/Videos/MIPS32/Sort/design/data_path.v
  /home/maji/Videos/MIPS32/Sort/design/full_adder.v
  /home/maji/Videos/MIPS32/Sort/design/half_adder.v
  /home/maji/Videos/MIPS32/Sort/design/instruction_decoder.v
  /home/maji/Videos/MIPS32/Sort/design/left_shift_32bit.v
  /home/maji/Videos/MIPS32/Sort/design/logical_right_shift_32bit.v
  /home/maji/Videos/MIPS32/Sort/design/sign_ext.v
  /home/maji/Videos/MIPS32/Sort/design/step_decoder.v
  /home/maji/Videos/MIPS32/Sort/design/top_module.v
}
read_ip -quiet /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.srcs/sources_1/ip/data_memory/data_memory.xci
set_property used_in_implementation false [get_files -all /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.gen/sources_1/ip/data_memory/data_memory_ooc.xdc]

read_ip -quiet /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.srcs/sources_1/ip/instr_memory/instr_memory.xci
set_property used_in_implementation false [get_files -all /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.gen/sources_1/ip/instr_memory/instr_memory_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/maji/Videos/MIPS32/Sort/constraint/temp.xdc
set_property used_in_implementation false [get_files /home/maji/Videos/MIPS32/Sort/constraint/temp.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/maji/Videos/MIPS32/Sort/sortingproject/sortingproject.srcs/utils_1/imports/synth_1/top_module.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_module -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
