# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/maji/Videos/MIPS32/CMOV_HAM/boothproject/boothproject.srcs/sources_1/ip/instr_memory/instr_memory.xci
# IP: The module: 'instr_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/maji/Videos/MIPS32/CMOV_HAM/boothproject/boothproject.gen/sources_1/ip/instr_memory/instr_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/maji/Videos/MIPS32/CMOV_HAM/boothproject/boothproject.srcs/sources_1/ip/instr_memory/instr_memory.xci
# IP: The module: 'instr_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/maji/Videos/MIPS32/CMOV_HAM/boothproject/boothproject.gen/sources_1/ip/instr_memory/instr_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
