# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Sujan/Downloads/final_project/final_project.runs/synth_1/top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Sujan/Downloads/final_project/final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Sujan/Downloads/final_project/final_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Sujan/Downloads/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Sujan/Downloads/mem_file.coe
add_files C:/Users/Sujan/Downloads/data_file.coe
add_files {{C:/Users/Sujan/Downloads/mem_file - 1.coe}}
add_files C:/Users/Sujan/Downloads/booth_data.coe
add_files C:/Users/Sujan/Downloads/booth_ins.coe
add_files C:/Users/Sujan/Downloads/sort-ins.coe
read_verilog -library xil_defaultlib {
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/ALU.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/ALU_function.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/AND.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/AND_32.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/Adder_32.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/EightBitAdder.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/EightBitSubtractor.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/FourBitAdder.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/HAMM.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/HAMM_32.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/IN_REG.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/LMD.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/MUX.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/MUX1.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/MUX_16_to_1.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/MUX_2_to_1.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/MUX_32_to_1.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/MUX_4_to_1.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/MUX_8_to_1.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/OR.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/OR_32.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/PC.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/RB.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/SixteenAdder.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/XOR.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/XOR_32.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/arithmetic_right_shift_32bit.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/comparator_32.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/complementer.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/control_path.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/data_path.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/full_adder.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/half_adder.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/instruction_decoder.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/left_shift_32bit.v
  C:/Users/Sujan/Downloads/ALU_final.srcs/ALU_final.srcs/sources_1/new/logical_right_shift_32bit.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/sign_ext.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/step_decoder.v
  C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/new/top_module.v
}
read_ip -quiet C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/ip/instr_memory/instr_memory.xci
set_property used_in_implementation false [get_files -all c:/Users/Sujan/Downloads/final_project/final_project.gen/sources_1/ip/instr_memory/instr_memory_ooc.xdc]

read_ip -quiet C:/Users/Sujan/Downloads/final_project/final_project.srcs/sources_1/ip/data_memory/data_memory.xci
set_property used_in_implementation false [get_files -all c:/Users/Sujan/Downloads/final_project/final_project.gen/sources_1/ip/data_memory/data_memory_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Sujan/Downloads/final_project/final_project.srcs/constrs_1/new/temp.xdc
set_property used_in_implementation false [get_files C:/Users/Sujan/Downloads/final_project/final_project.srcs/constrs_1/new/temp.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Sujan/Downloads/final_project/final_project.srcs/utils_1/imports/synth_1/top_module.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_module -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
